plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    implementation group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-fabric", version: "${whitenoise_version}"

/*
    runtimeOnly "dev.architectury:architectury-fabric:${architectury_version}"
    runtimeOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
*/
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${rei_version}"
    /*
     * TODO Re-enable REI when it is released
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    */

    compileOnly "mezz.jei:jei-${jei_minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-fabric:${jei_version}"

    runtimeOnly group: 'com.terraformersmc', name: 'modmenu', version: "${mod_menu_version}"
}

loom {
    def aw = project(":Common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            source sourceSets.test
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
        commonDatagen {
            client()
            setConfigName("${mod_name} Common Datagen")
            vmArg "-D${mod_id}.common_datagen=1"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../Common/src/generated/resources")}"
        }
        fabricTestDatagen {
            client()
            source sourceSets.test
            setConfigName("${mod_name} Fabric Test Datagen")
            vmArg "-D${mod_id}.fabric_test_datagen=1"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/test/resources")}"
        }
        neoForgeTestDatagen {
            client()
            source sourceSets.test
            setConfigName("${mod_name} NeoForge Test Datagen")
            vmArg "-D${mod_id}.neoforge_test_datagen=1"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../NeoForge/src/test/resources")}"
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId "${mod_id}-${minecraft_version}-fabric"
            version project.version
            from components.java
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                url 'file://' + System.getenv('local_maven')
            }
        }
    }
}
